### ISSUE TITLE
这只是一条站内信

### ISSUE THREAD

**Issue by Yaindrop** [AdamYuan/CubeCraft#1]
你好，抱歉通过这种方式联系，因为想不到其它的方式。我是手艺服的雨滴，不知你是否还记得。
偶然想起我们大概有着共同的兴趣爱好，不如认识一下，加个QQ吧。出于信息安全的考虑，请发邮件至theoriginer@hotmail.com，我看到后会立即回复😊

**Comment by AdamYuan** [comment]
很抱歉我不用qq，要么微信吧，我微信号y139166191212017年2月25日 下午10:29，Yaindrop <notifications@github.com>写道：你好，抱歉通过这种方式联系，因为想不到其它的方式。我是手艺服的雨滴，不知你是否还记得。
偶然想起我们大概有着共同的兴趣爱好，不如认识一下，加个QQ吧。出于信息安全的考虑，请发邮件至theoriginer@hotmail.com，我看到后会立即回复😊

**Comment by Yaindrop** [comment]
我搜索这个号码好像没有结果…你扫一下这个吧
[image1.PNG]

Sent from my iPhone

On 25 Feb 2017, at 22:48, AdamYuan <notifications@github.com<mailto:notifications@github.com>> wrote:

很抱歉我不用qq，要么微信吧，我微信号y139166191212017年2月25日 下午10:29，Yaindrop <notifications@github.com<mailto:notifications@github.com>>写道：你好，抱歉通过这种方式联系，因为想不到其它的方式。我是手艺服的雨滴，不知你是否还记得。
偶然想起我们大概有着共同的兴趣爱好，不如认识一下，加个QQ吧。出于信息安全的考虑，请发邮件至theoriginer@hotmail.com<mailto:theoriginer@hotmail.com>，我看到后会立即回复😊

**Comment by AdamYuan** [comment]
为何看不到图片。。。

**Comment by Yaindrop** [comment]
或许是因为客户端的原因...试试这个微信ID YD_Raindrop
On 25 Feb 2017, at 11:14 PM, AdamYuan <notifications@github.com<mailto:notifications@github.com>> wrote:


为何看不到图片。。。
